### ISSUE TITLE
R-Portable distribution for latest R version (4.0.3) and how to generate it

### ISSUE THREAD

**Issue by gdurif** [rer145/R-Portable#1]
Hi,

Thanks for these portable versions of R. Would that be possible to get a new release for the latest R (4.0.3)?

In addition, how do you generate these distributions? I am really interested in the recipe. If you do not have time or resources to continue upgrading R-Portable maybe we could help each other.

Best regards

**Comment by rer145** [comment]
Hi @gdurif , I didn't create this, but copied it over from https://sourceforge.net/projects/rportable/

It looks like they have version 4.0.0 available there.

**Comment by gdurif** [comment]
Hi @rer145, there is only a Windows version on https://sourceforge.net/projects/rportable/, where did you manage to get the MacOS one? I already had the Windows version, I am really interested in the MacOS one.
Thanks

**Comment by rer145** [comment]
Originally I found the MacOS version from here:  https://github.com/ColumbusCollaboratory/electron-quick-start

If you look at the commits for the mac folder (https://github.com/ColumbusCollaboratory/electron-quick-start/commits/master/R-Portable-Mac), you might be able see some of the modifications to the R source code that they had to make. I remember seeing an article about some of the changes, but I can't seem to find it anymore.

**Comment by gdurif** [comment]
Ok thanks
